apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-container
#  namespace:
spec:
  selector:
    matchLabels:
      app: hello-world-container
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-container
    spec:
      containers:
        - name: hello-world-container
          image: technicallyjoe/hello-world-container:1.0.1
