apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-configmap
data:
  HWC_SLEEPTIMER: "20"
  HWC_PRINTVAR: "true"
  HWC_TIMEDKILL: "false"
  HWC_EXITCODE: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-secret
type: Opaque
data:
  THISVALUEISVERYSECRET: cHJvZHVjdF9yb2JvdA==
  THISVALUEISVERYSECRETTOO: cHIwZHIwYjB0
#stringData:
#  THISVALUEISVERYSECRET: cHJvZHVjdF9yb2JvdA==
#  THISVALUEISVERYSECRETTOO: cHIwZHIwYjB0
#  You can also use stringData instead of data and instead use unencoded values,
#  Kubernetes then encodes the values for you when you create or update the secret.
#  This is useful when your deployment process generates configuration,
#  and you want to set the value at this stage.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
#  namespace:
spec:
  selector:
    matchLabels:
      app: hello-world-label
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-label
    spec:
      containers:
        - name: hello-world-container
          image: technicallyjoe/hello-world-container:1.0.7
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: hello-world-configmap
            - secretRef:
                name: hello-world-secret
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world-label
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: hello-world-label
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  #namespace: test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "test.myowndomain.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-service
                port:
                  number: 80
