version: "3.9"

services:
  hello-world-container:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      HWC_SLEEPTIMER: "5"
      HWC_PRINTVAR: "true"
    ports:
      - 80:80
